name: Build Flutter Project

on:
  push:
    branches:
      - master  # Trigger the workflow on push to main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3  # Checkout your repository

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.2'  # Specify the Flutter version you want to use

    - name: Build APK
      run: flutter build apk --release

    - name: Build IPA
      run: flutter build ipa --release --no-codesign  # No code signing for simplicity

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: |
          build/app/outputs/flutter-apk/app-release.apk
          build/ios/ipa/*.ipa
